all: main

main:
	@echo " Compile search...";
	
	g++ -O2 -I ./include -o build/search examples/main_search.cpp src/input_menu_starting_func.cpp src/lsh_basic_functions.cpp src/knn_ranges_brutes.cpp src/cube_basic_functions.cpp Fred/src/config.cpp Fred/src/curve.cpp Fred/src/frechet.cpp Fred/src/interval.cpp Fred/src/point.cpp Fred/src/simplification.cpp src/discrete_cont.cpp